name: Docker Image CI

on:
  push:
    branches: 
      - cicd

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: pandemiia/image-pandemiia
        registry: docker.pkg.github.com
        dockerfile: docker/app/Dockerfile
        username: ${{ github.actor }}
        password: ${{ secrets.CUSTOM_TOKEN }} 