name: Docker Image CI

on:
  push:
    branches: 
      - cicd

jobs:


  deploy:
    #needs: [build]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Play Ansible Playbook
      uses: arillso/action.playbook@0.0.2
      with:
          inventory: ansible/inventory
          playbook: ansible/develop.yml
          extra_vars: tag=${{ github.sha }}  CUSTOM_TOKEN=${{ secrets.CUSTOM_TOKEN }} actor=${{ github.actor }}
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'



