name: Docker Image CI

on:
  push:
    branches: 
      - cicd

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: pandemiia/pandemiia-image
        registry: docker.pkg.github.com
        githubOrg: pandemiia
        dockerfile: docker/app/Dockerfile_develop
        tag: ${{ github.sha }}
        username: ${{ github.actor }}
        password: ${{ secrets.CUSTOM_TOKEN }} 

  deploy:
    needs: [build]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Execute Ansible Playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        playbookName: 'ansible/develop.yml'
        inventoryFile: 'ansible/inventory'
        # If inventoryFile is set you can also specify a custom roles path to install your required roles in.
        rolesPath: # optional
        # Keyfile to use for host connections.
        keyFile: "pandemiia_key"
        extraVars: "-e tag=${{ github.sha }} -e CUSTOM_TOKEN=${{ secrets.CUSTOM_TOKEN }} -e actor=${{ github.actor }}"
        # File containing extra vars.
        extraFile: # optional