name: Docker Image CI

on:
  push:
    branches: 
      - cicd

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: pandemiia/pandemiia-image
        registry: docker.pkg.github.com
        githubOrg: pandemiia
        dockerfile: docker/app/Dockerfile_develop
        username: ${{ github.actor }}
        password: ${{ secrets.CUSTOM_TOKEN }} 

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: SSH
      run: |
       which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - name: SSH
      run: |
       eval $(ssh-agent -s)
    - name: SSH
      run: |
       echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
    - name: SSH
      run: |
       mkdir -p ~/.ssh
    - name: SSH
      run: |
       chmod 700 ~/.ssh
    - name: SSH
      run: |
       ssh-keyscan api.pandemiia.in.ua >> ~/.ssh/known_hosts
    - name: SSH
      run: |
       chmod 644 ~/.ssh/known_hosts


    - name: Execute Ansible Playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        playbookName: 'ansible/develop.yml'
        inventoryFile: 'ansible/inventory'
        # name of the requirements file to use.
        requirementsFile: # optional
        # If inventoryFile is set you can also specify a custom roles path to install your required roles in.
        rolesPath: # optional
        # Keyfile to use for host connections.
        keyFile: # optional
        # Vault Password to decrypt keyFile.
        keyFileVaultPass: # optional
        extraVars: 
        # File containing extra vars.
        extraFile: # optional