name: Docker Image CI

on:
  push:
    branches: 
      - cicd

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: pandemiia/pandemiia-image
        registry: docker.pkg.github.com
        githubOrg: pandemiia
        dockerfile: docker/app/Dockerfile_develop
        username: ${{ github.actor }}
        password: ${{ secrets.CUSTOM_TOKEN }} 

  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: SSH
      run: |
       which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y ) |
       eval $(ssh-agent -s) |
       echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null |
       mkdir -p ~/.ssh |
       chmod 700 ~/.ssh |
       ssh-keyscan api.pandemiia.in.ua >> ~/.ssh/known_hosts |
       chmod 644 ~/.ssh/known_hosts


    - name: Execute Ansible Playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        playbookName: 'ansible/develop.yml'
        inventoryFile: 'ansible/inventory'
        # name of the requirements file to use.
        requirementsFile: # optional
        # If inventoryFile is set you can also specify a custom roles path to install your required roles in.
        rolesPath: # optional
        # Keyfile to use for host connections.
        keyFile: "pandemiia_key"
        # Vault Password to decrypt keyFile.
        keyFileVaultPass: # optional
        extraVars: "-e image=${{ github.sha }} -e tag=${{ github.sha }}"
        # File containing extra vars.
        extraFile: # optional