name: Docker Image CI

on:
  push:
    branches: 
      - cicd

jobs:


  deploy:
    #needs: [build]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: Execute Ansible Playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        playbookName: 'ansible/develop.yml'
        inventoryFile: 'ansible/inventory'
        keyFile: $key
        extraVars: "-e key=${{ secrets.SSH_PRIVATE_KEY }} -e tag=${{ github.sha }} -e CUSTOM_TOKEN=${{ secrets.CUSTOM_TOKEN }} -e actor=${{ github.actor }}"