name: Docker Image CI

on:
  push:
    branches: 
      - cicd

jobs:

 

  deploy:
    #needs: [build]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out code

    - name: SSH
      run: |
       which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y ) 

    - name: SSH
      run: |
       eval $(ssh-agent -s) 
   
    - name: SSH
      run: |
       mkdir -p ~/.ssh 
    - name: SSH
      run: |
       chmod 700 ~/.ssh 
    - name: SSH
      run: |
       ssh-keyscan api.pandemiia.in.ua >> ~/.ssh/known_hosts
    - name: SSH
      run: |
       chmod 644 ~/.ssh/known_hosts

    - name: Execute Ansible Playbook
      uses: saubermacherag/ansible-playbook-docker-action@v1.3
      with:
        playbookName: 'ansible/develop.yml'
        inventoryFile: 'ansible/inventory'
        keyFile:
        extraVars: "-e tag=${{ github.sha }} -e CUSTOM_TOKEN=${{ secrets.CUSTOM_TOKEN }} -e actor=${{ github.actor }}"