# Generated by Django 3.0.4 on 2020-03-25 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Категорія товару')),
            ],
            options={
                'verbose_name': 'Категорії товарів',
            },
        ),
        migrations.CreateModel(
            name='HospitalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Назва медзакладу')),
                ('city', models.CharField(max_length=200, verbose_name='Місто/населений пункт')),
            ],
            options={
                'verbose_name': 'Госпіталі',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Назва товару')),
                ('units', models.IntegerField(choices=[(0, 'шт'), (1, 'уп'), (2, 'фл')], default=0, verbose_name='Одиниці вимірювання')),
                ('count', models.IntegerField(verbose_name='Кількість')),
                ('status', models.IntegerField(choices=[(0, 'Є потреба'), (1, 'Отримано')], default=0, verbose_name='Статус')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('last_edited_on', models.DateTimeField(auto_now=True, verbose_name='Востаннє відредаговано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.CategoryModel')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.HospitalModel')),
            ],
            options={
                'verbose_name': 'Товари',
            },
        ),
    ]
