# Generated by Django 3.0.4 on 2020-04-01 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('description', models.CharField(max_length=1000, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='CategoryArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Категорія товару')),
            ],
            options={
                'verbose_name': 'Категорія товарів',
                'verbose_name_plural': 'Категорії товарів',
            },
        ),
        migrations.CreateModel(
            name='CategoryPointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Категорія закладів')),
            ],
            options={
                'verbose_name': 'Категорія закладів',
                'verbose_name_plural': 'Категорії закладів',
            },
        ),
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ПІБ контактної особи')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Посада')),
                ('email', models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Телефонний номер має бути в форматі +380123456789', regex='^\\+?3?8?(0\\d{9})$')], verbose_name='Контактний телефон')),
            ],
            options={
                'verbose_name': 'Контактна особа',
                'verbose_name_plural': 'Контактні особи',
            },
        ),
        migrations.CreateModel(
            name='PointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Назва медзакладу')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Опис')),
                ('region', models.IntegerField(choices=[(0, '----'), (1, 'Вінницька область'), (2, 'Волинська область'), (3, 'Дніпропетровська область'), (4, 'Донецька область'), (5, 'Житомирська область'), (6, 'Закарпатська область'), (7, 'Запорізька область'), (8, 'Івано-Франківська область'), (9, 'Київська область'), (10, 'Кіровоградська область'), (11, 'Луганська область'), (12, 'Львівська область'), (13, 'Миколаївська область'), (14, 'Одеська область'), (15, 'Полтавська область'), (16, 'Рівненська область'), (17, 'Сумська область'), (18, 'Тернопільська область'), (19, 'Харківська область'), (20, 'Херсонська область'), (21, 'Хмельницька область'), (22, 'Черкаська область'), (23, 'Чернівецька область'), (24, 'Чернігівська область'), (25, 'м. Київ')], default=0, verbose_name='Область')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('zip_code', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Поштовий індекс має бути в форматі 01234', regex='^\\d{5}$')], verbose_name='Поштовий індекс')),
                ('line1', models.CharField(max_length=50, verbose_name='Повний адрес')),
                ('geo_lat', models.IntegerField(blank=True, null=True, verbose_name='Геопозиція: широта')),
                ('geo_lng', models.IntegerField(blank=True, null=True, verbose_name='Геопозиція: довгота')),
                ('category', models.ManyToManyField(to='medsupport.models.HospitalCategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логін користувача')),
            ],
            options={
                'verbose_name': 'Медичний заклад',
                'verbose_name_plural': 'Медичні заклади',
            },
        ),
        migrations.CreateModel(
            name='PhoneContactPersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=13, verbose_name='Контактний телефон')),
                ('contact_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.models.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='NeedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.PositiveIntegerField(default=0, verbose_name='Скільки ще потрібно')),
                ('quantity_done', models.PositiveIntegerField(default=0, verbose_name='Скільки вже отримано')),
                ('units', models.IntegerField(choices=[(0, 'шт'), (1, 'уп'), (2, 'фл')], default=0, verbose_name='Одиниці вимірювання')),
                ('status', models.IntegerField(choices=[(0, 'Є потреба'), (1, 'Отримано')], default=0, verbose_name='Статус')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення')),
                ('last_edited_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Востаннє відредаговано')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.models.Solution')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.models.Point', verbose_name='Лікарня')),
            ],
            options={
                'verbose_name': 'Потреба',
                'verbose_name_plural': 'Потреби',
            },
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='medsupport.models.Point'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ManyToManyField(to='medsupport.models.SolutionCategory', verbose_name='Категорії'),
        ),
    ]
