# Generated by Django 3.0.4 on 2020-03-25 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlemodel',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товари'},
        ),
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Категорія товарів', 'verbose_name_plural': 'Категорії товарів'},
        ),
        migrations.AlterModelOptions(
            name='hospitalmodel',
            options={'verbose_name': 'Госпіталь', 'verbose_name_plural': 'Госпіталі'},
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='hospital',
            new_name='Госпіталь',
        ),
        migrations.RenameField(
            model_name='articlemodel',
            old_name='category',
            new_name='Категорія',
        ),
    ]
