# Generated by Django 3.0.4 on 2020-04-20 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medsupport', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='medsupport.Hospital'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospital',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Логін користувача'),
        ),
    ]
