# Generated by Django 3.0.4 on 2020-03-29 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medsupport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneContactPersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=13, verbose_name='Контактний телефон')),
            ],
        ),
        migrations.CreateModel(
            name='PointContactPersonModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, verbose_name='ПІБ контактної особи')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Посада')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='PointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Назва медзакладу')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Опис')),
                ('region', models.IntegerField(choices=[(0, '----'), (1, 'Вінницька область'), (2, 'Волинська область'), (3, 'Дніпропетровська область'), (4, 'Донецька область'), (5, 'Житомирська область'), (6, 'Закарпатська область'), (7, 'Запорізька область'), (8, 'Івано-Франківська область'), (9, 'Київська область'), (10, 'Кіровоградська область'), (11, 'Луганська область'), (12, 'Львівська область'), (13, 'Миколаївська область'), (14, 'Одеська область'), (15, 'Полтавська область'), (16, 'Рівненська область'), (17, 'Сумська область'), (18, 'Тернопільська область'), (19, 'Харківська область'), (20, 'Херсонська область'), (21, 'Хмельницька область'), (22, 'Черкаська область'), (23, 'Чернівецька область'), (24, 'Чернігівська область'), (25, 'м. Київ')], default=0, verbose_name='Область')),
                ('city', models.CharField(max_length=50, verbose_name='Місто')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Поштовий індекс')),
                ('line1', models.CharField(max_length=50, verbose_name='Повний адрес')),
                ('geo_lat', models.IntegerField(verbose_name='Геопозиція: широта')),
                ('geo_lng', models.IntegerField(verbose_name='Геопозиція: довгота')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Госпіталь',
                'verbose_name_plural': 'Госпіталі',
            },
        ),
        migrations.DeleteModel(
            name='ArticleModel',
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
        migrations.DeleteModel(
            name='HospitalModel',
        ),
        migrations.AddField(
            model_name='pointcontactpersonmodel',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.PointModel'),
        ),
        migrations.AddField(
            model_name='phonecontactpersonmodel',
            name='contact_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.PointContactPersonModel'),
        ),
    ]
