# Generated by Django 3.0.4 on 2020-04-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointmodel',
            name='geo_lat',
        ),
        migrations.RemoveField(
            model_name='pointmodel',
            name='geo_lng',
        ),
    ]
