# Generated by Django 3.0.4 on 2020-03-25 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0002_auto_20200325_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='Категорія',
            new_name='category',
        ),
    ]
