# Generated by Django 3.0.4 on 2020-04-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0002_auto_20200401_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointmodel',
            name='geo_lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Геопозиція: широта (lat)'),
        ),
        migrations.AddField(
            model_name='pointmodel',
            name='geo_lng',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Геопозиція: довгота (lng)'),
        ),
    ]
