# Generated by Django 3.0.4 on 2020-03-29 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0002_auto_20200329_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointcontactpersonmodel',
            name='tel',
            field=models.CharField(blank=True, max_length=13, verbose_name='Контактний телефон'),
        ),
        migrations.AlterField(
            model_name='pointmodel',
            name='geo_lat',
            field=models.IntegerField(blank=True, verbose_name='Геопозиція: широта'),
        ),
        migrations.AlterField(
            model_name='pointmodel',
            name='geo_lng',
            field=models.IntegerField(blank=True, verbose_name='Геопозиція: довгота'),
        ),
    ]
