# Generated by Django 3.0.4 on 2020-04-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0002_auto_20200420_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва матеріалу')),
            ],
            options={
                'verbose_name': 'Матеріал',
                'verbose_name_plural': 'Матеріали',
            },
        ),
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва інструменту')),
            ],
            options={
                'verbose_name': 'Засіб',
                'verbose_name_plural': 'Засоби',
            },
        ),
        migrations.RemoveField(
            model_name='solution',
            name='description',
        ),
        migrations.AddField(
            model_name='solution',
            name='code',
            field=models.CharField(default=1, max_length=10, verbose_name='Код товару'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='definition',
            field=models.TextField(default=1, max_length=1000, verbose_name='Визначення'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solution',
            name='need_description',
            field=models.TextField(default=1, max_length=1000, verbose_name='Опис потреби'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solution',
            name='attachment',
            field=models.FileField(upload_to='solution_attachment', verbose_name='Архів з файлами'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='instruction',
            field=models.TextField(max_length=1000, verbose_name='Інструкція'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='main_image',
            field=models.ImageField(upload_to='solution_images', verbose_name='Головне зображення'),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='materials',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='tools',
        ),
        migrations.AddField(
            model_name='solution',
            name='materials',
            field=models.ManyToManyField(to='medsupport.Material', verbose_name='Матеріали, з яких можна виготовляти'),
        ),
        migrations.AddField(
            model_name='solution',
            name='tools',
            field=models.ManyToManyField(to='medsupport.Tool', verbose_name='Засоби для виготовлення'),
        ),
    ]
