# Generated by Django 3.0.4 on 2020-04-15 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0003_auto_20200401_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointmodel',
            name='line1',
            field=models.CharField(max_length=100, verbose_name='Повний адрес'),
        ),
    ]
