# Generated by Django 3.0.4 on 2020-03-29 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0003_auto_20200329_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPointModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Категорія закладів')),
            ],
            options={
                'verbose_name': 'Категорія закладів',
                'verbose_name_plural': 'Категорії закладів',
            },
        ),
        migrations.AlterModelOptions(
            name='pointcontactpersonmodel',
            options={'verbose_name': 'Контактна особа', 'verbose_name_plural': 'Контактні особи'},
        ),
        migrations.AddField(
            model_name='pointmodel',
            name='category',
            field=models.ManyToManyField(to='medsupport.CategoryPointModel'),
        ),
    ]
