# Generated by Django 3.0.4 on 2020-03-25 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0003_auto_20200325_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlemodel',
            old_name='Госпіталь',
            new_name='hospital',
        ),
    ]
