# Generated by Django 3.0.4 on 2020-04-17 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0004_auto_20200415_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='approved_by',
            field=models.CharField(blank=True, max_length=200, verbose_name='Ким затверджено'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='attachment',
            field=models.FileField(blank=True, upload_to='article_attachment', verbose_name='Прикріплений файл'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='instruction',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Інструкція'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='article_images', verbose_name='Головне зображення'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='materials',
            field=models.CharField(blank=True, max_length=200, verbose_name='Матеріали, з яких можна виготовляти'),
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='tools',
            field=models.CharField(blank=True, max_length=200, verbose_name='Засоби для виготовлення'),
        ),
    ]
