# Generated by Django 3.0.4 on 2020-03-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0004_auto_20200329_1825'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('description', models.CharField(max_length=1000, verbose_name='Опис')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
            },
        ),
        migrations.CreateModel(
            name='CategoryArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, verbose_name='Категорія товару')),
            ],
            options={
                'verbose_name': 'Категорія товарів',
                'verbose_name_plural': 'Категорії товарів',
            },
        ),
        migrations.CreateModel(
            name='NeedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_needed', models.IntegerField(verbose_name='Скільки ще потрібно')),
                ('quantity_done', models.IntegerField(verbose_name='Скільки вже отримано')),
                ('units', models.IntegerField(choices=[(0, 'шт'), (1, 'уп'), (2, 'фл')], default=0, verbose_name='Одиниці вимірювання')),
                ('status', models.IntegerField(choices=[(0, 'Є потреба'), (1, 'Отримано')], default=0, verbose_name='Статус')),
                ('created_on', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення')),
                ('last_edited_on', models.DateTimeField(auto_now=True, null=True, verbose_name='Востаннє відредаговано')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.ArticleModel')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.PointModel', verbose_name='Лікарня')),
            ],
            options={
                'verbose_name': 'Потреба',
                'verbose_name_plural': 'Потреби',
            },
        ),
        migrations.AddField(
            model_name='articlemodel',
            name='category',
            field=models.ManyToManyField(to='medsupport.CategoryArticleModel', verbose_name='Категорії'),
        ),
    ]
