# Generated by Django 3.0.4 on 2020-04-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0004_auto_20200420_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='code',
            field=models.CharField(default='-', max_length=10, verbose_name='Код товару'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='instruction',
            field=models.TextField(max_length=1000, verbose_name='Варіанти виготовлення'),
        ),
    ]
