# Generated by Django 3.0.4 on 2020-03-29 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0005_auto_20200329_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointmodel',
            name='geo_lat',
            field=models.IntegerField(blank=True, null=True, verbose_name='Геопозиція: широта'),
        ),
        migrations.AlterField(
            model_name='pointmodel',
            name='geo_lng',
            field=models.IntegerField(blank=True, null=True, verbose_name='Геопозиція: довгота'),
        ),
    ]
