# Generated by Django 3.0.4 on 2020-03-25 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medsupport', '0005_auto_20200325_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvisionerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(blank=True, max_length=13)),
                ('hospital', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='medsupport.HospitalModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Провізор',
                'verbose_name_plural': 'Провізори',
            },
        ),
    ]
