# Generated by Django 3.0.4 on 2020-04-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0005_auto_20200417_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointmodel',
            name='company_code',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код ЄДРПОУ'),
        ),
        migrations.AddField(
            model_name='pointmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Електронна адреса установи'),
        ),
    ]
