# Generated by Django 3.0.4 on 2020-04-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0005_auto_20200420_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='attachment',
            field=models.CharField(blank=True, max_length=200, verbose_name='Посилання на завантаження архіву'),
        ),
    ]
