# Generated by Django 3.0.4 on 2020-03-25 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0006_provisionermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionermodel',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medsupport.HospitalModel'),
        ),
    ]
