# Generated by Django 3.0.4 on 2020-04-17 20:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medsupport', '0006_auto_20200417_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointmodel',
            name='user',
        ),
        migrations.AddField(
            model_name='pointmodel',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Логін користувача'),
        ),
    ]
