# Generated by Django 3.0.4 on 2020-03-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('medsupport', '0006_auto_20200329_2015'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointContactPersonModel',
            new_name='ContactModel',
        ),
        migrations.AlterField(
            model_name='needmodel',
            name='quantity_done',
            field=models.IntegerField(default=0, verbose_name='Скільки вже отримано'),
        ),
        migrations.AlterField(
            model_name='needmodel',
            name='quantity_needed',
            field=models.IntegerField(default=0, verbose_name='Скільки ще потрібно'),
        ),
    ]
