# Generated by Django 3.0.4 on 2020-04-17 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0007_auto_20200417_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='needmodel',
            name='status',
        ),
    ]
