# Generated by Django 3.0.4 on 2020-03-25 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0007_auto_20200325_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionermodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='provisionermodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ПІБ'),
        ),
    ]
