# Generated by Django 3.0.4 on 2020-03-29 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0007_auto_20200329_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='medsupport.PointModel'),
        ),
    ]
