# Generated by Django 3.0.4 on 2020-03-30 05:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medsupport', '0008_auto_20200329_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='tel',
        ),
        migrations.AddField(
            model_name='contactmodel',
            name='phone',
            field=models.CharField(blank=True, max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Телефонний номер має бути в форматі +380123456789', regex='^\\+?3?8?(0\\d{9})$')], verbose_name='Контактний телефон'),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='needmodel',
            name='quantity_done',
            field=models.PositiveIntegerField(default=0, verbose_name='Скільки вже отримано'),
        ),
        migrations.AlterField(
            model_name='needmodel',
            name='quantity_needed',
            field=models.PositiveIntegerField(default=0, verbose_name='Скільки ще потрібно'),
        ),
        migrations.AlterField(
            model_name='pointmodel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Логін користувача'),
        ),
    ]
