# Generated by Django 3.0.4 on 2020-03-30 05:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0009_auto_20200330_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointmodel',
            name='zip_code',
            field=models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator(message='Поштовий індекс має бути в форматі 01234', regex='^\\d{5}$')], verbose_name='Поштовий індекс'),
        ),
    ]
