# Generated by Django 3.0.4 on 2020-03-25 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0009_auto_20200325_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalmodel',
            old_name='city',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.CategoryModel', verbose_name='Категорія'),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.HospitalModel', verbose_name='Лікарня'),
        ),
        migrations.AlterField(
            model_name='provisionermodel',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medsupport.HospitalModel', verbose_name='Лікарня'),
        ),
    ]
