# Generated by Django 3.0.4 on 2020-03-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0010_auto_20200325_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlemodel',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medsupport.ProvisionerModel', verbose_name='Автор'),
        ),
    ]
