# Generated by Django 3.0.4 on 2020-05-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0010_auto_20200501_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedBy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_name', models.CharField(blank=True, max_length=200, verbose_name='Назва організації')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='approved_by_logo', verbose_name='Логотип установи')),
            ],
            options={
                'verbose_name': 'Ким затверджено',
                'verbose_name_plural': 'Ким затверджені',
            },
        ),
        migrations.RemoveField(
            model_name='solution',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='categories',
        ),
        migrations.AddField(
            model_name='solution',
            name='comment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Короткий коментар від затверджувача'),
        ),
        migrations.AddField(
            model_name='solutiontype',
            name='categories',
            field=models.ManyToManyField(to='medsupport.SolutionCategory', verbose_name='Категорії'),
        ),
    ]
