# Generated by Django 3.0.4 on 2020-04-30 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0010_auto_20200430_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalneed',
            name='solution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_type', to='medsupport.SolutionType', verbose_name='Тип рішення'),
        ),
    ]
