# Generated by Django 3.0.4 on 2020-03-31 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0010_auto_20200330_0808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pointmodel',
            options={'verbose_name': 'Медичний заклад', 'verbose_name_plural': 'Медичні заклади'},
        ),
    ]
