# Generated by Django 3.0.4 on 2020-03-25 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0011_articlemodel_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medsupport.HospitalModel', verbose_name='Госпіталь'),
        ),
    ]
