# Generated by Django 3.0.4 on 2020-05-04 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0011_auto_20200504_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='medsupport.ApprovedBy', verbose_name='Ким затверджено'),
        ),
    ]
