# Generated by Django 3.0.4 on 2020-03-25 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0012_auto_20200325_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='hospital',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medsupport.HospitalModel', verbose_name='Лікарня'),
            preserve_default=False,
        ),
    ]
