# Generated by Django 3.0.4 on 2020-03-25 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('medsupport', '0013_auto_20200325_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='author',
        ),
        migrations.AddField(
            model_name='hospitalmodel',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='hospitalmodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='ПІБ контактної особи'),
        ),
        migrations.AddField(
            model_name='hospitalmodel',
            name='tel',
            field=models.CharField(blank=True, max_length=13, verbose_name='Контактний телефон'),
        ),
        migrations.AddField(
            model_name='hospitalmodel',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProvisionerModel',
        ),
    ]
