# Generated by Django 3.0.4 on 2020-05-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0014_auto_20200505_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='instruction',
            new_name='manufacturing_options',
        ),
        migrations.AlterField(
            model_name='solution',
            name='attachment',
            field=models.URLField(blank=True, verbose_name='Посилання на файли'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='need_description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Опис потреби'),
        ),
    ]
