# Generated by Django 3.0.4 on 2020-05-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0015_auto_20200519_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='solution',
            name='instruction',
            field=models.URLField(blank=True, verbose_name='Посилання на інструкцію'),
        ),
    ]
