# Generated by Django 3.0.4 on 2020-03-27 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0016_auto_20200326_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='count',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='last_edited_on',
        ),
        migrations.RemoveField(
            model_name='articlemodel',
            name='status',
        ),
        migrations.CreateModel(
            name='HospitalNeedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Кількість')),
                ('status', models.IntegerField(choices=[(0, 'Є потреба'), (1, 'Отримано')], default=0, verbose_name='Статус')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('last_edited_on', models.DateTimeField(auto_now=True, verbose_name='Востаннє відредаговано')),
                ('article', models.ManyToManyField(to='medsupport.ArticleModel')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medsupport.HospitalModel', verbose_name='Лікарня')),
            ],
            options={
                'verbose_name': 'Потреба',
                'verbose_name_plural': 'Потреби',
            },
        ),
    ]
