# Generated by Django 3.0.4 on 2020-03-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0017_auto_20200327_2217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalneedmodel',
            name='created_on',
        ),
    ]
