# Generated by Django 3.0.4 on 2020-03-27 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0018_remove_hospitalneedmodel_created_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalneedmodel',
            name='last_edited_on',
        ),
    ]
