# Generated by Django 3.0.4 on 2020-03-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0019_remove_hospitalneedmodel_last_edited_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='units',
        ),
        migrations.AddField(
            model_name='hospitalneedmodel',
            name='units',
            field=models.IntegerField(choices=[(0, 'шт'), (1, 'уп'), (2, 'фл')], default=0, verbose_name='Одиниці вимірювання'),
        ),
    ]
