# Generated by Django 3.0.4 on 2020-03-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0020_auto_20200327_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalneedmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата створення'),
        ),
        migrations.AddField(
            model_name='hospitalneedmodel',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Востаннє відредаговано'),
        ),
    ]
