# Generated by Django 3.0.4 on 2020-03-27 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medsupport', '0021_auto_20200327_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalneedmodel',
            name='article',
        ),
        migrations.AddField(
            model_name='hospitalneedmodel',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medsupport.ArticleModel'),
            preserve_default=False,
        ),
    ]
